### ISSUE TITLE
[Formatting] LGU Night Vision runs onto 2nd line

### ISSUE THREAD

**Issue by JohnMetroid** [Rminin/FinallyCorrectKeys#1]
Hey there,

Really enjoying your mod.  It's nice to finally have all the in-game prompts showing accurate binds :)

Not sure if this is due to a character limit for each line or something else, but just figured I'd log this for you in case it was an easy fix.

![image](https://github.com/user-attachments/assets/e04fa665-a03f-4a90-8d7c-a47688ec7fa2)

Cheers

**Comment by Rminin** [comment]
Heyo, thanks for the info. I never used Unity but I looked into it ingame with the UnityInspector. For me it seemed like the standard width of the control tip lines or their parent container was too small for the name of the Night Vision Goggles. I found that by disabling word wrap, the text will stay on the same line (obviously 😅). So here's a comparison:

Before, standard behaviour:
![Screenshot 2024-12-22 041416](https://github.com/user-attachments/assets/af461138-464f-4972-8662-ab767ad815da)

After, word wrap disabled:
![Screenshot 2024-12-22 041330](https://github.com/user-attachments/assets/edee92cb-fdfe-4abf-9d76-648c96a58fae)

This is implemented in v1.2.2.

This could impact mods that rely on the word wrap being enabled, but I wouldn't know any that do.
